
Description = "vim clarity"

Default	= { Colour="#b2dfee" }
Canvas	= { Colour="#1F3055" }
Number	= { Colour="#b3ee3a" }
Escape	= { Colour="#FFEEA6" }
String	= { Colour="#cccccc" }
BlockComment	= { Colour="#9e9e9e" }
StringPreProc = String
LineComment   = BlockComment
Operator      = Default
LineNum      = BlockComment
PreProcessor      = Default
Interpolation  = { Colour="#CEFF9F" }

Keywords = {
  { Colour="#cd919e" },
  { Colour="#ff4400" },
  { Colour="#9ecc91" },
  { Colour="#edc1b2" },
}
