#############################################################################
# Makefile for building: highlight-gui
# Generated by qmake (3.0) (Qt 5.0.0) on: Mi 30. Jan 21:50:03 2013
# Project:  src\w32-projects\highlight_gui\highlight.pro
# Template: app
# Command: d:\devel\qt-everywhere-opensource-src-5.0.0\qtbase\bin\qmake.exe -spec win32-g++ -o Makefile src\w32-projects\highlight_gui\highlight.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = d:\devel\qt-everywhere-opensource-src-5.0.0\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: src/w32-projects/highlight_gui/highlight.pro ../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/spec_pre.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/device_config.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/common/shell-win32.conf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/qconfig.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_axbase.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_axbase.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_axcontainer.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_axserver.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_axserver.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_bootstrap.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_clucene.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_clucene.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_concurrent.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_core.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_declarative.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_declarative.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_designer.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_designer.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_designercomponents.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_gui.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_help.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_help.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_multimedia.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_multimediawidgets.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_network.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_opengl.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_platformsupport.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_printsupport.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_qml.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_qmldevtools.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_qmltest.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_qtmultimediaquicktools.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_quick.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_quick.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_quickparticles.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_script.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_script.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_scripttools.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_sql.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_svg.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_svg.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_testlib.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_uitools.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_v8.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_v8.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_widgets.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_xml.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_dsengine.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qdeclarativeview.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qmng.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qtga.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/qt_functions.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/qt_config.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/win32-g++/qmake.conf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/spec_post.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/default_pre.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/win32/default_pre.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/release.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/debug_and_release.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/default_post.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/static.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/win32/rtti.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/warn_on.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/qt.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/resources.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/moc.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/win32/opengl.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/win32/windows.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/testcase_targets.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/exceptions.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/yacc.prf \
		../../../../devel/qt-everywhere-opensource-src-5.0.0/qtbase/mkspecs/features/lex.prf \
		src/w32-projects/highlight_gui/highlight.pro \
		D:/devel/qt-everywhere-opensource-src-5.0.0/qtbase/plugins/platforms/qwindows.prl \
		D:/Devel/qt-everywhere-opensource-src-5.0.0/qtbase/lib/Qt5PlatformSupport.prl \
		D:/Devel/qt-everywhere-opensource-src-5.0.0/qtbase/lib/Qt5Gui.prl \
		D:/Devel/qt-everywhere-opensource-src-5.0.0/qtbase/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ -o Makefile src\w32-projects\highlight_gui\highlight.pro
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\spec_pre.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\device_config.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\common\shell-win32.conf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\qconfig.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_axbase.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_axcontainer.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_axserver.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_bootstrap.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_bootstrap.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_clucene.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_clucene.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_concurrent.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_core.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_core.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_declarative.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_declarative.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_designer.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_designer.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_designercomponents.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_designercomponents.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_gui.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_gui.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_help.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_help.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_network.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_network.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_opengl.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_platformsupport.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_platformsupport.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_printsupport.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_qml.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_qml.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_qmldevtools.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_qmltest.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_qtmultimediaquicktools.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_quick.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_quick.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_quickparticles.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_quickparticles.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_script.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_script.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_sql.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_sql.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_svg.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_svg.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_testlib.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_v8.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_v8.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_widgets.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_xml.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_xml.pri:
..\..\..\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_dsengine.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qdeclarativeview.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qico.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qminimal.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qmldbg_inspector.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qmldbg_qtquick2.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp_qtdeclarative.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qmng.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qsvg.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qsvgicon.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qtaccessiblequick.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qtaccessiblewidgets.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qtga.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qtiff.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qwbmp.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_qwindows.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\qt_functions.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\qt_config.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\win32-g++\qmake.conf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\spec_post.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\exclusive_builds.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\default_pre.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\win32\default_pre.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\release.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\debug_and_release.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\default_post.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\static.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\win32\rtti.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\warn_on.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\qt.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\resources.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\moc.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\win32\opengl.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\win32\windows.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\testcase_targets.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\exceptions.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\yacc.prf:
..\..\..\..\devel\qt-everywhere-opensource-src-5.0.0\qtbase\mkspecs\features\lex.prf:
src\w32-projects\highlight_gui\highlight.pro:
D:/devel/qt-everywhere-opensource-src-5.0.0/qtbase/plugins/platforms/qwindows.prl:
D:/Devel/qt-everywhere-opensource-src-5.0.0/qtbase/lib/Qt5PlatformSupport.prl:
D:/Devel/qt-everywhere-opensource-src-5.0.0/qtbase/lib/Qt5Gui.prl:
D:/Devel/qt-everywhere-opensource-src-5.0.0/qtbase/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile src\w32-projects\highlight_gui\highlight.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) precomp.h.gch\c
	-$(DEL_FILE) precomp.h.gch\c++
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) D:\Devel\cpp\syntaxhighlight-code\highlight\highlight-gui_plugin_import.cpp

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
